### ISSUE TITLE
Could this become a built in Gnome feature?

### ISSUE THREAD

**Issue by dreua** [p91paul/middleclickclose#24]
Did anyone try? What would it take?

**Comment by p91paul** [comment]
AFAIK nobody did.
You could try opening an issue on the gnome bug tracker and see if it gains traction.
That would be nice, since this extension modifies the behavior of internal gnome functions and because of that can easily break (like it did in 3.38 and does in gnome 40).

**Comment by dreua** [comment]
Turns out it has already been done:
[Add middle click and close button on switch windows to quit app (#1390) · Issues · GNOME / gnome-shell · GitLab](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1390)
[Middle-click to close windows from Activities overview (#1174) · Issues · GNOME / gnome-shell · GitLab](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1174)

**Comment by p91paul** [comment]
I've added my 2 cents there, but I don't really count on them to act on it since GNOME team is very opinionated about UX.
Which IMHO is good for consistency in appearance and behavior (which is admittedly very good across GNOME apps), bad for the number of extensions you need to install (and for me, maintain) to get the functionality they don't feel it's appropriate.

**Comment by dreua** [comment]
I fully agree and like to add a third "bad": it's also bad for the users which need to figure out what they are missing first and then search and install those extensions. I've been using Gnome for years and only recently came up with the idea that "middleclickclose" could be a great thing, and, luckily found your extension. Now I can't imagine life without it :smile:
