### ISSUE TITLE
Update for GNOME 3.18

### ISSUE THREAD

**Issue by kparal** [p91paul/middleclickclose#4]
Hello,

GNOME 3.18 has been released and many people already use it. Could you please update your extension at extensions.gnome.org to support this new GNOME version?

Thanks!

**Comment by p91paul** [comment]
Hi,
Actually I'm not yet a 3.18 user, I'm waiting for Arch Linux to update it in stable repositories (I believe this will happen in a few days). I hope the update is nothing more than a metadata.json edit, but can't tell for sure.

Could you try to add 3.18 to supported versions in metadata.json? if it works for you and at least another person, I will update earlier.

Instead of making the modification myself after your or someone else's test, I'd rather accept a pull request, just so that the person who actually commited their time to this is mentioned in the list of contributors here on github.

**Comment by kparal** [comment]
I simply disabled extension version validation in gnome-shell and there seems to be no issue with this extension. I think you can consider it working.

**Comment by p91paul** [comment]
Didn't know disabling extension version validation was a thing :) thanks for testing and for teaching me something!

**Comment by kparal** [comment]
You're welcome:
http://worldofgnome.org/an-easy-way-to-test-extensions-compatibility-in-gnome-3-12/

And thank you for maintaining this very useful extension.

**Comment by p91paul** [comment]
uploaded to e.g.o. and awaiting review!
